language: python
python:
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov


script:
  - "pytest --with-coverage --cover-package=app"

after_success:
  - coveralls