language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov


script:
  - "python --with-coverage --cover-package=app app/"

after_success:
  - coveralls